# cSpell:disable

# Imports
spring.config.import=classpath:config/private.properties

# Configuraciones de la aplicacion
spring.application.name=BigoBooks

# Swagger (creo)
springdoc.api-docs.enabled=false

# Base de datos
spring.datasource.url=${db.url}?user=${db.username}&password=${db.password}

# Jpa
spring.jpa.hibernate.ddl-auto=none

# Liquibase
spring.liquibase.enabled=false