# cSpell:disable

# Imports
spring.config.import=classpath:private.properties

# Configuraciones de la aplicacion
spring.application.name=BigoBooks

# Swagger (creo)
springdoc.api-docs.enabled=false

# Base de datos
spring.datasource.url=${db.url}?user=${db.username}&password=${db.password}

# Jpa
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

# Liquibase
spring.liquibase.enabled=false